import { writeFile, readFile, mkdir } from "node:fs/promises";
import path from "node:path";
import type { SkillStats, GapEntry, CompanyStats, MapData, FitResult, Freshness } from "./types.js";
import { atomicWrite } from "./io.js";
import { compareJobs, type RankableJob } from "./fit.js";
import type { TimelineMonth } from "./timeline.js";

const ARROW = { rising: "↑", stable: "→", declining: "↓" } as const;
const GEN_HEADER = (now: Date) =>
  `<!-- AUTO-GENERATED by the indexer. DO NOT EDIT. generated: ${now.toISOString()} -->\n\n`;

export async function emitJson(dataDir: string, name: string, payload: unknown): Promise<void> {
  await mkdir(dataDir, { recursive: true });
  await writeFile(path.join(dataDir, name), JSON.stringify(payload, null, 2), "utf8");
}

export function renderSkillCloud(stats: SkillStats[], now: Date): string {
  const rows = stats.filter(s => s.count > 0).map(s =>
    `| [[${s.name}]] | ${s.count} | ${(s.share * 100).toFixed(0)}% | ${s.tier} | ${ARROW[s.trend]} | ${s.have ? "✅" : "❌"} |`);
  return GEN_HEADER(now) + `# Skill Cloud\n\n| Skill | Active jobs | Share | Tier | Trend | Have |\n|---|---|---|---|---|---|\n${rows.join("\n")}\n`;
}

export function renderCompanies(companies: CompanyStats[], now: Date): string {
  const rows = companies.map(c =>
    `| [[${c.name}]] | ${c.active} | ${c.total} | ${c.avgSalary ? "$" + c.avgSalary.toLocaleString() : "—"} | ${(c.remoteShare * 100).toFixed(0)}% | ${c.repeatPoster ? "yes" : "no"} |`);
  return GEN_HEADER(now) + `# Companies Hiring\n\n| Company | Active | All-time | Avg salary | Remote share | Repeat poster |\n|---|---|---|---|---|---|\n${rows.join("\n")}\n`;
}

export function renderLocations(map: MapData, now: Date): string {
  const rows = map.places.map(p => `| ${p.place} | ${p.count} | ${p.jobs.map(j => `[[${j}]]`).join(", ")} |`);
  return GEN_HEADER(now) + `# Locations\n\n| Place | Active jobs | Postings |\n|---|---|---|\n${rows.join("\n")}\n\nRemote: **${map.remoteCount}** · Elsewhere: **${map.otherCount}**\n`;
}

export function renderFitRanking(jobs: ({ name: string } & RankableJob & { fit: FitResult; freshness: Freshness })[], now: Date): string {
  const rows = [...jobs].sort(compareJobs).map(j =>
    `| [[${j.name}]] | ${j.fit.score} | ${j.fit.tier} | ${j.freshness} |`);
  return GEN_HEADER(now) + `# Fit Ranking\n\n| Posting | Fit | Tier | Freshness |\n|---|---|---|---|\n${rows.join("\n")}\n`;
}

export function renderTrends(stats: SkillStats[], now: Date): string {
  const moving = stats.filter(s => s.trend !== "stable" && s.count > 0);
  const rows = moving.map(s => `| [[${s.name}]] | ${ARROW[s.trend]} ${s.trend} | ${s.count} |`);
  return GEN_HEADER(now) + `# Trends\n\n| Skill | Trend | Active jobs |\n|---|---|---|\n${rows.join("\n")}\n`;
}

function gapTable(gaps: GapEntry[]): string {
  const rows = gaps.map(g =>
    `| [[${g.name}]] | ${g.roi} | ${g.count} | ${(g.share * 100).toFixed(0)}% | ${ARROW[g.trend]} | ${g.closedBy.map(p => `[[${p}]]`).join(", ") || "—"} |`);
  return `| Missing skill | ROI | Active jobs | Share | Trend | Closed by project |\n|---|---|---|---|---|---|\n${rows.join("\n")}`;
}

export async function injectGapBlock(file: string, gaps: GapEntry[]): Promise<void> {
  const BEGIN = "<!-- gap:begin -->", END = "<!-- gap:end -->";
  const block = `${BEGIN}\n${gapTable(gaps)}\n${END}`;
  let raw: string;
  try {
    raw = await readFile(file, "utf8");
  } catch {
    await mkdir(path.dirname(file), { recursive: true });
    await atomicWrite(file,
      `---\ntype: coach\ncreated: ${new Date().toISOString().slice(0, 10)}\nupdated: ${new Date().toISOString().slice(0, 10)}\n---\n\n# Skill Gap Analysis\n\n${block}\n\n## Commentary\n\n(LLM commentary goes here and survives regeneration.)\n`);
    return;
  }
  const start = raw.indexOf(BEGIN), end = raw.indexOf(END);
  if (start === -1 || end === -1 || end < start) throw new Error(`gap markers not found or inverted in ${file}`);
  const next = raw.slice(0, start) + block + raw.slice(end + END.length);
  // Skip identical rewrites: this file lives inside the server's watched dirs, and an
  // unconditional tmp+rename here would re-poke the watcher forever (reindex loop).
  if (next === raw) return;
  await atomicWrite(file, next);
}
